version: "3.7"

services: 
  service1:
    image: lamhuynhb779/swarm-run-service:php
    networks: 
      - net1
    ports:
      - 8085:8085
    deploy: 
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure

  service2:
    image: lamhuynhb779/swarm-run-service:dotnet
    networks: 
      - net2
    ports:
      - 8086:8085
    deploy: 
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure 
networks:
  net1:
  # If you dont define then it will use default network overlay
  net2:
    driver: overlay
    name: www-net2
