version: "3.7"

services: 
  service1:
    image: lamhuynhb779/swarm-run-service:php
    ports:
      - 8085:8085
    deploy: 
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure

  service2:
    image: lamhuynhb779/swarm-run-service:dotnet
    ports:
      - 8086:8085
    deploy: 
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure 